#!/usr/bin/env python3
"""
Sirraya QuTub — Publication-Quality Experimental Plots
========================================================

Reads CSV datasets generated by the Sirraya QuTub Rust
visualization example and produces publication-quality PNG
figures.

Expected directory layout:

    QuTub-Core/
    └── scripts/
        ├── plot.py
        ├── validation_output/
        │   ├── state_vector_scaling.csv
        │   ├── qft_scaling.csv
        │   ├── fidelity_vs_depth.csv
        │   ├── bell_distribution.csv
        │   ├── ghz_entanglement.csv
        │   ├── w_state.csv
        │   └── noise_vs_purity.csv
        └── docs/

Run from anywhere:

    python scripts/plot.py

or from scripts/:

    python plot.py

Requirements:

    pip install pandas matplotlib numpy
"""

from pathlib import Path
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib


# ============================================================================
# PATHS
# ============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent

DATA_DIR = SCRIPT_DIR / "validation_output"
OUTPUT_DIR = SCRIPT_DIR / "docs"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================================
# PLOTTING CONFIGURATION
# ============================================================================

matplotlib.rcParams["font.family"] = "DejaVu Sans"

plt.rcParams.update({
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.labelsize": 11,
    "legend.fontsize": 9,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "axes.grid": True,
    "grid.alpha": 0.25,
    "lines.linewidth": 1.8,
})


# ============================================================================
# HELPERS
# ============================================================================

def banner(title):
    print()
    print("=" * 72)
    print(title)
    print("=" * 72)


def require_file(filename):
    path = DATA_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"\nRequired dataset not found:\n"
            f"  {path}\n\n"
            f"Run the Rust generator first:\n"
            f"  cargo run --release --example visualization"
        )

    return path


def read_csv(filename):
    path = require_file(filename)
    df = pd.read_csv(path)

    if df.empty:
        raise ValueError(
            f"\nDataset is empty:\n"
            f"  {path}"
        )

    return df


def require_columns(df, filename, columns):
    missing = [c for c in columns if c not in df.columns]

    if missing:
        raise ValueError(
            f"\nDataset schema mismatch:\n"
            f"  {DATA_DIR / filename}\n\n"
            f"Missing columns:\n"
            f"  {missing}\n\n"
            f"Available columns:\n"
            f"  {list(df.columns)}"
        )


def save_figure(fig, filename):
    path = OUTPUT_DIR / filename
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    print(f"  -> {path}")


def first_existing_column(df, candidates):
    """
    Return the first candidate column that exists.
    """
    for name in candidates:
        if name in df.columns:
            return name

    return None


def numeric_series(df, column):
    """
    Convert a dataframe column to numeric values.

    Invalid values become NaN and are removed by the caller
    when appropriate.
    """
    return pd.to_numeric(df[column], errors="coerce")


def clean_xy(df, x_column, y_column):
    """
    Return finite numeric x/y arrays.
    """
    x = numeric_series(df, x_column)
    y = numeric_series(df, y_column)

    mask = np.isfinite(x) & np.isfinite(y)

    return x[mask].to_numpy(), y[mask].to_numpy()


# ============================================================================
# 1. STATE-VECTOR SCALING
# ============================================================================

def plot_state_vector_scaling():
    print("1. State-vector scaling")

    filename = "state_vector_scaling.csv"
    df = read_csv(filename)

    require_columns(
        df,
        filename,
        [
            "qubits",
            "state_dimension",
        ],
    )

    qubits = numeric_series(df, "qubits")
    dimension = numeric_series(df, "state_dimension")

    mask = np.isfinite(qubits) & np.isfinite(dimension)

    qubits = qubits[mask].to_numpy()
    dimension = dimension[mask].to_numpy()

    if len(qubits) == 0:
        raise ValueError(
            f"No valid numeric data found in {filename}."
        )

    fig, ax = plt.subplots(figsize=(8, 5))

    ax.semilogy(
        qubits,
        dimension,
        "o-",
        label="State-vector dimension",
    )

    ax.set_xlabel("Number of Qubits")
    ax.set_ylabel("State-Vector Dimension")
    ax.set_title("Sirraya QuTub State-Vector Scaling")

    ax.set_xticks(qubits)

    ax.legend(loc="upper left")

    # ------------------------------------------------------------------
    # Optional timing data.
    #
    # Actual observed schema:
    #
    # qubits
    # state_dimension
    # construction_ms
    # hadamard_chain_ms
    # ------------------------------------------------------------------

    timing_columns = []

    if "construction_ms" in df.columns:
        timing_columns.append("construction_ms")

    if "hadamard_chain_ms" in df.columns:
        timing_columns.append("hadamard_chain_ms")

    if timing_columns:
        ax2 = ax.twinx()

        for column in timing_columns:
            y = numeric_series(df.loc[mask], column).to_numpy()

            if column == "construction_ms":
                ax2.plot(
                    qubits,
                    y,
                    "s--",
                    label="Construction time",
                )

            elif column == "hadamard_chain_ms":
                ax2.plot(
                    qubits,
                    y,
                    "^-.",
                    label="Hadamard-chain time",
                )

        ax2.set_ylabel("Runtime (ms)")

        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()

        ax.legend(
            lines1 + lines2,
            labels1 + labels2,
            loc="upper left",
        )

    fig.tight_layout()
    save_figure(fig, "state_vector_scaling.png")


# ============================================================================
# 2. QFT SCALING
# ============================================================================

def plot_qft_scaling():
    print("2. QFT scaling")

    filename = "qft_scaling.csv"
    df = read_csv(filename)

    require_columns(
        df,
        filename,
        ["qubits"],
    )

    time_col = first_existing_column(
        df,
        [
            "qft_ms",
            "qft_us",
            "runtime_ms",
            "time_ms",
            "duration_ms",
            "qft_time_ms",
            "execution_ms",
            "execution_us",
        ],
    )

    if time_col is None:
        raise ValueError(
            f"\nCould not find a QFT timing column in {filename}.\n\n"
            f"Available columns:\n"
            f"  {list(df.columns)}\n\n"
            f"Expected one of:\n"
            f"  qft_ms\n"
            f"  qft_us\n"
            f"  runtime_ms\n"
            f"  time_ms\n"
            f"  duration_ms\n"
            f"  qft_time_ms\n"
            f"  execution_ms\n"
            f"  execution_us"
        )

    x, y = clean_xy(df, "qubits", time_col)

    if len(x) == 0:
        raise ValueError(
            f"No valid numeric QFT timing data found in {filename}."
        )

    fig, ax = plt.subplots(figsize=(8, 5))

    ax.semilogy(
        x,
        y,
        "o-",
        label="QFT",
    )

    if time_col.endswith("_us"):
        unit = "µs"
    else:
        unit = "ms"

    ax.set_xlabel("Number of Qubits")
    ax.set_ylabel(f"QFT Runtime ({unit})")
    ax.set_title(
        "Sirraya QuTub Quantum Fourier Transform Scaling"
    )

    ax.set_xticks(x)

    ax.legend()

    fig.tight_layout()
    save_figure(fig, "qft_scaling.png")


# ============================================================================
# 3. FIDELITY VS CIRCUIT DEPTH
# ============================================================================

def plot_fidelity_vs_depth():
    print("3. Fidelity vs circuit depth")

    filename = "fidelity_vs_depth.csv"
    df = read_csv(filename)

    require_columns(
        df,
        filename,
        ["depth"],
    )

    # Actual observed schema:
    #
    # depth
    # ideal_vs_perturbed_fidelity
    # trace_distance
    #
    fidelity_col = first_existing_column(
        df,
        [
            "fidelity",
            "ideal_vs_perturbed_fidelity",
            "self_fidelity",
        ],
    )

    if fidelity_col is None:
        raise ValueError(
            f"\nCould not find fidelity column in {filename}.\n\n"
            f"Available columns:\n"
            f"  {list(df.columns)}"
        )

    x, fidelity = clean_xy(
        df,
        "depth",
        fidelity_col,
    )

    if len(x) == 0:
        raise ValueError(
            f"No valid fidelity data found in {filename}."
        )

    fig, ax = plt.subplots(figsize=(8, 5))

    ax.plot(
        x,
        fidelity,
        "o-",
        label=fidelity_col.replace("_", " "),
    )

    ax.axhline(
        1.0,
        linestyle="--",
        linewidth=1,
        label="Ideal fidelity = 1",
    )

    ax.set_xlabel("Circuit Depth")
    ax.set_ylabel("Fidelity")
    ax.set_title(
        "Sirraya QuTub Fidelity vs Circuit Depth"
    )

    minimum = float(np.min(fidelity))
    maximum = float(np.max(fidelity))

    # If fidelity is extremely close to one, zoom in.
    if (
        maximum <= 1.000001
        and minimum >= 0.999
    ):
        span = maximum - minimum

        margin = max(
            span * 5.0,
            1e-6,
        )

        lower = max(
            0.0,
            minimum - margin,
        )

        upper = min(
            1.000001,
            maximum + margin,
        )

        ax.set_ylim(lower, upper)

    ax.legend()

    fig.tight_layout()
    save_figure(
        fig,
        "fidelity_vs_depth.png",
    )


# ============================================================================
# 4. BELL-STATE MEASUREMENT DISTRIBUTION
# ============================================================================

def plot_bell_distribution():
    print("4. Bell-state measurement distribution")

    filename = "bell_distribution.csv"
    df = read_csv(filename)

    # Actual schema:
    #
    # basis_state, probability
    #

    require_columns(
        df,
        filename,
        [
            "basis_state",
            "probability",
        ],
    )

    print(f"  Columns: {list(df.columns)}")

    labels = df["basis_state"].astype(str)

    probability = numeric_series(
        df,
        "probability",
    )

    mask = np.isfinite(probability)

    labels = labels[mask].to_numpy()
    probability = probability[mask].to_numpy()

    if len(probability) == 0:
        raise ValueError(
            f"No valid probability data found in {filename}."
        )

    fig, ax = plt.subplots(figsize=(7, 5))

    positions = np.arange(len(labels))

    ax.bar(
        positions,
        probability,
    )

    ax.set_xticks(positions)
    ax.set_xticklabels(labels)

    ax.set_xlabel("Computational Basis State")
    ax.set_ylabel("Probability")
    ax.set_title(
        "Bell-State Measurement Distribution"
    )

    upper = max(
        0.6,
        float(np.max(probability)) * 1.15,
    )

    ax.set_ylim(
        0,
        upper,
    )

    for i, value in enumerate(probability):
        ax.text(
            i,
            value + 0.015,
            f"{value:.3f}",
            ha="center",
            fontsize=10,
        )

    fig.tight_layout()
    save_figure(
        fig,
        "bell_distribution.png",
    )


# ============================================================================
# 5. GHZ ENTANGLEMENT
# ============================================================================

def plot_ghz_entanglement():
    print("5. GHZ entanglement")

    filename = "ghz_entanglement.csv"
    df = read_csv(filename)

    # Actual Rust-generated schema:
    #
    # qubits
    # p_all_zero
    # p_all_ones
    # forbidden_probability
    #
    require_columns(
        df,
        filename,
        [
            "qubits",
            "p_all_zero",
            "p_all_ones",
            "forbidden_probability",
        ],
    )

    # Convert everything explicitly to numeric.
    qubits = pd.to_numeric(
        df["qubits"],
        errors="coerce",
    )

    p_zero = pd.to_numeric(
        df["p_all_zero"],
        errors="coerce",
    )

    p_ones = pd.to_numeric(
        df["p_all_ones"],
        errors="coerce",
    )

    forbidden = pd.to_numeric(
        df["forbidden_probability"],
        errors="coerce",
    )

    mask = (
        np.isfinite(qubits)
        & np.isfinite(p_zero)
        & np.isfinite(p_ones)
        & np.isfinite(forbidden)
    )

    qubits = qubits[mask].to_numpy()
    p_zero = p_zero[mask].to_numpy()
    p_ones = p_ones[mask].to_numpy()
    forbidden = forbidden[mask].to_numpy()

    if len(qubits) == 0:
        raise ValueError(
            f"No valid numeric GHZ data found in {filename}."
        )

    print(
        f"  GHZ rows: {len(qubits)}"
    )

    # ------------------------------------------------------------------
    # GHZ validation:
    #
    # |GHZ_n> = (|00...0> + |11...1>) / sqrt(2)
    #
    # Therefore:
    #
    # P(00...0) = 0.5
    # P(11...1) = 0.5
    # P(forbidden states) = 0
    # ------------------------------------------------------------------

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(12, 4.8),
    )

    # ==================================================================
    # Panel 1 — Allowed GHZ measurement probabilities
    # ==================================================================

    axes[0].plot(
        qubits,
        p_zero,
        "o-",
        label="P(|00...0⟩)",
    )

    axes[0].plot(
        qubits,
        p_ones,
        "s-",
        label="P(|11...1⟩)",
    )

    axes[0].axhline(
        0.5,
        linestyle="--",
        linewidth=1,
        label="Theory = 0.5",
    )

    axes[0].set_xlabel(
        "Number of Qubits"
    )

    axes[0].set_ylabel(
        "Measurement Probability"
    )

    axes[0].set_title(
        "GHZ Allowed-State Probabilities"
    )

    axes[0].set_ylim(
        0.0,
        1.0,
    )

    axes[0].set_xticks(
        qubits
    )

    axes[0].legend()

    # ==================================================================
    # Panel 2 — Forbidden probability
    # ==================================================================

    axes[1].plot(
        qubits,
        forbidden,
        "o-",
        label="Forbidden probability",
    )

    axes[1].axhline(
        0.0,
        linestyle="--",
        linewidth=1,
        label="Theory = 0",
    )

    axes[1].set_xlabel(
        "Number of Qubits"
    )

    axes[1].set_ylabel(
        "Probability"
    )

    axes[1].set_title(
        "GHZ Forbidden-State Probability"
    )

    axes[1].set_xticks(
        qubits
    )

    # If numerical error is tiny, don't let matplotlib make the graph
    # look completely flat without context.
    max_forbidden = float(
        np.max(np.abs(forbidden))
    )

    if max_forbidden == 0.0:
        axes[1].set_ylim(
            -1e-12,
            1e-12,
        )
    else:
        margin = max(
            max_forbidden * 0.25,
            1e-12,
        )

        axes[1].set_ylim(
            min(0.0, float(np.min(forbidden)) - margin),
            float(np.max(forbidden)) + margin,
        )

    axes[1].legend()

    fig.suptitle(
        "Sirraya QuTub GHZ State Validation",
        fontsize=14,
    )

    fig.tight_layout()

    save_figure(
        fig,
        "ghz_entanglement.png",
    )

# ============================================================================
# 6. W-STATE VALIDATION
# ============================================================================

def plot_w_state():
    print("6. W-state amplitudes / probabilities")

    filename = "w_state.csv"
    df = read_csv(filename)

    require_columns(
        df,
        filename,
        ["qubits"],
    )

    value_col = first_existing_column(
        df,
        [
            "probability",
            "amplitude",
            "single_excitation_probability",
            "expected_probability",
        ],
    )

    if value_col is None:
        numeric = df.select_dtypes(
            include=[np.number]
        ).columns.tolist()

        candidates = [
            c
            for c in numeric
            if c != "qubits"
        ]

        if candidates:
            value_col = candidates[0]

    if value_col is None:
        raise ValueError(
            f"\nCould not determine W-state observable "
            f"in {filename}.\n\n"
            f"Available columns:\n"
            f"  {list(df.columns)}"
        )

    x, y = clean_xy(
        df,
        "qubits",
        value_col,
    )

    if len(x) == 0:
        raise ValueError(
            f"No valid W-state data found in {filename}."
        )

    fig, ax = plt.subplots(figsize=(8, 5))

    ax.plot(
        x,
        y,
        "o-",
        label=value_col.replace(
            "_",
            " ",
        ),
    )

    ax.set_xlabel("Number of Qubits")
    ax.set_ylabel(
        value_col.replace(
            "_",
            " ",
        ).title()
    )

    ax.set_title(
        "Sirraya QuTub W-State Validation"
    )

    ax.legend()

    fig.tight_layout()

    save_figure(
        fig,
        "w_state.png",
    )


# ============================================================================
# 7. NOISE VS PURITY
# ============================================================================

def plot_noise_vs_purity():
    print("7. Noise vs purity")

    filename = "noise_vs_purity.csv"
    df = read_csv(filename)

    # Actual schema observed:
    #
    # noise_probability
    # purity
    # von_neumann_entropy
    #
    # Previous script incorrectly expected:
    #
    # probability
    #

    noise_col = first_existing_column(
        df,
        [
            "noise_probability",
            "probability",
            "noise_strength",
            "noise",
            "p",
            "gamma",
        ],
    )

    if noise_col is None:
        raise ValueError(
            f"\nCould not find noise-probability column "
            f"in {filename}.\n\n"
            f"Available columns:\n"
            f"  {list(df.columns)}\n\n"
            f"Expected one of:\n"
            f"  noise_probability\n"
            f"  probability\n"
            f"  noise_strength\n"
            f"  noise\n"
            f"  p\n"
            f"  gamma"
        )

    purity_col = first_existing_column(
        df,
        [
            "purity",
            "state_purity",
        ],
    )

    if purity_col is None:
        raise ValueError(
            f"\nCould not find purity column in {filename}.\n\n"
            f"Available columns:\n"
            f"  {list(df.columns)}"
        )

    x, purity = clean_xy(
        df,
        noise_col,
        purity_col,
    )

    if len(x) == 0:
        raise ValueError(
            f"No valid noise/purity data found "
            f"in {filename}."
        )

    fig, ax = plt.subplots(
        figsize=(8, 5)
    )

    # ------------------------------------------------------------------
    # If the Rust generator contains channel/model information,
    # plot separate curves.
    # ------------------------------------------------------------------

    grouping_column = None

    for candidate in [
        "channel",
        "noise_model",
        "model",
        "channel_type",
    ]:
        if candidate in df.columns:
            grouping_column = candidate
            break

    if grouping_column is not None:

        for group_name, subset in df.groupby(
            grouping_column
        ):
            sx, sy = clean_xy(
                subset,
                noise_col,
                purity_col,
            )

            if len(sx) == 0:
                continue

            ax.plot(
                sx,
                sy,
                "o-",
                label=str(group_name),
            )

    else:

        ax.plot(
            x,
            purity,
            "o-",
            label="Numerical",
        )

    ax.set_xlabel(
        "Noise Probability"
    )

    ax.set_ylabel(
        "Purity"
    )

    ax.set_title(
        "Sirraya QuTub Noise-Induced Purity"
    )

    ax.legend()

    fig.tight_layout()

    save_figure(
        fig,
        "noise_vs_purity.png",
    )


# ============================================================================
# OPTIONAL: NOISE ENTROPY
# ============================================================================

def plot_noise_entropy():
    """
    Generate an additional plot when the actual noise dataset provides
    von_neumann_entropy.

    This is useful because the current Rust dataset contains:

        noise_probability
        purity
        von_neumann_entropy
    """

    filename = "noise_vs_purity.csv"
    df = read_csv(filename)

    noise_col = first_existing_column(
        df,
        [
            "noise_probability",
            "probability",
            "noise_strength",
            "noise",
            "p",
            "gamma",
        ],
    )

    entropy_col = first_existing_column(
        df,
        [
            "von_neumann_entropy",
            "entropy",
        ],
    )

    if noise_col is None or entropy_col is None:
        return

    x, y = clean_xy(
        df,
        noise_col,
        entropy_col,
    )

    if len(x) == 0:
        return

    fig, ax = plt.subplots(
        figsize=(8, 5)
    )

    ax.plot(
        x,
        y,
        "o-",
        label="von Neumann entropy",
    )

    ax.set_xlabel(
        "Noise Probability"
    )

    ax.set_ylabel(
        "von Neumann Entropy (bits)"
    )

    ax.set_title(
        "Sirraya QuTub Noise-Induced Entropy"
    )

    ax.legend()

    fig.tight_layout()

    save_figure(
        fig,
        "noise_vs_entropy.png",
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print(
        "Generating plots from Sirraya QuTub experimental data...\n"
    )

    print("Script directory:")
    print(f"  {SCRIPT_DIR}")

    print("\nDataset directory:")
    print(f"  {DATA_DIR}")

    print("\nOutput directory:")
    print(f"  {OUTPUT_DIR}")

    if not DATA_DIR.exists():

        print(
            "\nERROR: Dataset directory does not exist:\n"
            f"  {DATA_DIR}\n"
        )

        sys.exit(1)

    csv_files = sorted(
        DATA_DIR.glob("*.csv")
    )

    print("\nCSV files detected:")

    if not csv_files:

        print("  (none)")

        sys.exit(1)

    for path in csv_files:
        print(
            f"  - {path.name}"
        )

    banner(
        "PLOT GENERATION"
    )

    # ------------------------------------------------------------------
    # Run every plot independently.
    #
    # This is deliberate: one malformed/optional dataset should not
    # prevent the other valid experimental figures from being produced.
    # ------------------------------------------------------------------

    jobs = [
        (
            "State-vector scaling",
            plot_state_vector_scaling,
        ),
        (
            "QFT scaling",
            plot_qft_scaling,
        ),
        (
            "Fidelity vs circuit depth",
            plot_fidelity_vs_depth,
        ),
        (
            "Bell-state measurement distribution",
            plot_bell_distribution,
        ),
        (
            "GHZ entanglement",
            plot_ghz_entanglement,
        ),
        (
            "W-state validation",
            plot_w_state,
        ),
        (
            "Noise vs purity",
            plot_noise_vs_purity,
        ),
        (
            "Noise vs entropy",
            plot_noise_entropy,
        ),
    ]

    successful = []
    failed = []

    for name, function in jobs:

        try:

            function()

            successful.append(name)

        except Exception as exc:

            failed.append(
                (
                    name,
                    str(exc),
                )
            )

            print()
            print(
                f"  WARNING: {name} failed."
            )

            print(
                f"  Reason: {exc}"
            )

            print(
                "  Continuing with remaining plots."
            )

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    banner(
        "PLOT GENERATION SUMMARY"
    )

    print(
        f"Successful plots: "
        f"{len(successful)}"
    )

    for name in successful:
        print(
            f"  [PASS] {name}"
        )

    if failed:

        print()
        print(
            f"Failed plots: "
            f"{len(failed)}"
        )

        for name, reason in failed:
            print(
                f"  [FAIL] {name}"
            )
            print(
                f"         {reason}"
            )

    print()
    print(
        "Generated files:"
    )

    generated = sorted(
        OUTPUT_DIR.glob("*.png")
    )

    if generated:

        for path in generated:
            print(
                f"  - {path.name}"
            )

    else:

        print(
            "  (none)"
        )

    print()
    print(
        f"Output directory:"
    )
    print(
        f"  {OUTPUT_DIR}"
    )

    # ------------------------------------------------------------------
    # Important:
    #
    # Optional/missing schema issues do not crash the whole script.
    # But if nothing could be generated, return an error code.
    # ------------------------------------------------------------------

    if not successful:

        print()
        print(
            "ERROR: No plots were generated."
        )

        sys.exit(1)

    print()
    print(
        "Done."
    )


if __name__ == "__main__":
    main()